export const iconRegistry = {
  // orangeBg: require('@/assets/images/orange-bg.png'),
  sample: require('@/assets/icons/sample.png'),
  close: require('@/assets/icons/close.png'),
  divideLine: require('@/assets/icons/divide-line.png'),

  arrowRight: require('@/assets/icons/splash/arrow-right.png'),

  home: require('@/assets/icons/tab_icon/home.png'),
  homeSeleted: require('@/assets/icons/tab_icon/home_selected.png'),
  add: require('@/assets/icons/tab_icon/add.png'),
  addSeleted: require('@/assets/icons/tab_icon/add_selected.png'),
  profile: require('@/assets/icons/tab_icon/profile.png'),
  profileSeleted: require('@/assets/icons/tab_icon/profile_selected.png'),
  launcherProfile: require('@/assets/icons/launcher-profile.png'),
  dogeCoinIcon: require('@/assets/icons/dogeCoinIcon.png'),
  addThin: require('@/assets/icons/add-thin.png'),
  apple: require('@/assets/icons/apple.png'),
  arrowUp: require('@/assets/icons/arrow-up.png'),
  arrowRightThick: require('@/assets/icons/arrow-right-thick.png'),
  backArrow: require('@/assets/icons/back-arrow.png'),

  chevronDown: require('@/assets/icons/chevron-down.png'),
  chevronUp: require('@/assets/icons/chevron-up.png'),
  chevronUpGrey: require('@/assets/icons/chevron-up-grey.png'),
  chevronDownGrey: require('@/assets/icons/chevron-down-grey.png'),
  filledCrossGrey: require('@/assets/icons/filled-cross-icon-grey.png'),
  copyLink: require('@/assets/icons/copy-link.png'),
  coins: require('@/assets/icons/coins.png'),
  coin: require('@/assets/icons/coin.png'),
  copy: require('@/assets/icons/copy.png'),

  depositPlaceholder: require('@/assets/icons/deposit-placeholder.png'),
  download: require('@/assets/icons/download.png'),
  info: require('@/assets/icons/info.png'),
  notification: require('@/assets/icons/notification.png'),
  search: require('@/assets/icons/search.png'),
  searchCircle: require('@/assets/icons/search-circle.png'),
  send: require('@/assets/icons/send.png'),

  setting: require('@/assets/icons/setting.png'),
  sendProfile: require('@/assets/icons/send-profile.png'),
  star: require('@/assets/icons/star.png'),
  starFilled: require('@/assets/icons/star-filled.png'),
  telegram: require('@/assets/icons/icon_telegram.png'),
  tick: require('@/assets/icons/tick.png'),
  tiktok: require('@/assets/icons/tiktok.png'),
  link_icon: require('@/assets/icons/link_icon.png'),

  trending: require('@/assets/icons/trending.png'),
  twitter: require('@/assets/icons/icon_twitter.png'),
  link: require('@/assets/icons/icon_link.png'),
  upload: require('@/assets/icons/upload.png'),
  uploadBlueIcon: require('@/assets/icons/uploadBlueIcon.png'),
  upArrowThick: require('@/assets/icons/up-arrow-thick.png'),
  userCircle: require('@/assets/icons/user-circle.png'),
  calculatorMinusIcon: require('@/assets/icons/calculatorMinusIcon.png'),

  wallet: require('@/assets/icons/wallet.png'),
  withdraw: require('@/assets/icons/withdraw.png'),
  // buttons backgrounds
  orangeButtonBackground: require('@/assets/icons/orange_button_background.png'),
  marketCapIcon: require('@/assets/icons/market_cap_icon.png'),
  volumeIcon: require('@/assets/icons/volume_icon.png'),
  circulatingIcon: require('@/assets/icons/circulating_icon.png'),
  supplyIcon: require('@/assets/icons/supply_icon.png'),
  createdIcon: require('@/assets/icons/created_icon.png'),
  websiteIcon: require('@/assets/icons/website_icon.png'),
  xIcon: require('@/assets/icons/x_icon.png'),
  telegramIcon: require('@/assets/icons/telegram_icon.png'),
  discordIcon: require('@/assets/icons/discord_icon.png'),
}
