import { StyleSheet } from 'react-native'
import { Colors } from '@/constants/Colors'

export const styles = StyleSheet.create({
  rowContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 24,
    paddingVertical: 8,
    paddingHorizontal: 16,
    backgroundColor: 'white',
    fontFamily: 'SfProRounded',
  },
  listItemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    fontFamily: 'SfProRounded',
    borderRadius: 16,
  },
  iconContainer: {
    width: 42,
    height: 42,
    backgroundColor: '#d9d9d9',
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'SfProRounded',
    borderRadius: 21,
  },
  icon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    fontFamily: 'SfProRounded',
  },
  infoOuterRowContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    fontFamily: 'SfProRounded',
    alignItems: 'center',
    gap: 8,
  },
  infoInnerColumnContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    fontFamily: 'SfProRounded',
    alignItems: 'flex-start',
    gap: 4,
  },
  username: {
    textAlign: 'center',
    color: '#70737d',
    fontSize: 12,
    fontWeight: '500',
    fontFamily: 'SfProRounded',
    lineHeight: 12,
  },
  nameText: {
    color: Colors.titleLight2,
    fontSize: 16,
    fontFamily: 'SfProRoundedBold',
    lineHeight: 19.2,
    fontWeight: '700',
  },
  symbolText: {
    fontFamily: 'SfProRoundedBold',
    fontSize: 14,
    color: Colors.cardBackgroundBlue,
    lineHeight: 19.2,
  },
  priceChangeContainer: {
    position: 'absolute',
    right: 0,
    top: 2,
  },
  priceChangeText: {
    color: Colors.valueUp,
    fontSize: 10,
    fontWeight: 'bold',
    fontFamily: 'SfProRounded',
    lineHeight: 10,
  },
  socialsAndDescriptionContainer: {
    flex: 1,
    flexGrow: 1,
    height: 16,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  socialsContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 7,
  },
  descriptionText: {
    color: Colors.subtitle,
    fontSize: 14,
    fontWeight: '500',
    fontFamily: 'SfProRoundedSemibold',
    lineHeight: 16.8,
  },
  metricsContainer: {
    flexShrink: 0,
    alignSelf: 'stretch',
    flexDirection: 'column',
    justifyContent: 'center',
  },
  marketCapContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  marketCapText: {
    color: Colors.lime,
    fontSize: 12,
    fontWeight: 'normal',
    fontFamily: 'SfProRounded',
  },
  marketCapAmount: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    fontFamily: 'SfProRounded',
  },
  marketCapAmountText: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    fontFamily: 'SfProRounded',
    fontSize: 16,
    lineHeight: 19.2,
  },
  marketCapPercentageText: {
    display: 'flex',
    flexDirection: 'row',
    color: Colors.titleLight,
    opacity: 0.5,
    justifyContent: 'flex-start',
    alignItems: 'center',
    gap: 2,
    fontSize: 16,
    fontWeight: '700',
    lineHeight: 19.2,
    fontFamily: 'SfProRoundedMedium',
  },
})
